### Reconnection Strategies

Everytime a Mule app starts, it runs a connectivity test on all its components, for example, the HTTP and FTP connectors. The HTTP and FTP connectors connect to an external server, and if the test fails, they log a warning message and continue with the app deployment by default.

You can modify this behavior by configuring the following:

- You set a number of reconnection attempts to try after an initial failure. 
- You force the deployment to fail when all connection attempts fail.

The following reconnection strategies allow you to modify the connectivity tests as follows:

* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. For example, you might set a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms). Defaults to 2 reconnection attempts at a frequency of `2000 ms`.
* Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and any configured reconnection attempts are exhausted.
* Reconnect Forever (reconnect-forever): Attempts to reconnect at a given interval, for example, every 4000 ms for as long as the app runs. The default interval is 2000 ms. There is no limit on the number of retries, so the value `count` is not specified.

The following XML file modifies the behavior of the connection by forcing the deployment to fail with the `failsDeployment` variable set to `true`. It does 5 reconnection attempts every 4000 ms.

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

The following XML file sets `reconnect-forever` to reconnect every 4000 ms:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connection>
----


